In [ ]:
import sys
import os
import numpy as np

custom_path = os.path.join(
    os.getcwd(), "/scr/matthewh6/robot_pref"
)  # or a relative/absolute path
if custom_path not in sys.path:
    sys.path.append(custom_path)

In [ ]:
from utils.env import get_robomimic_env, wrap_env
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv, DummyVecEnv


def make_env_fn(seed):
    def _init():
        env = get_robomimic_env(
            "/scr/shared/datasets/robot_pref/stack_mixed/stack_mixed.hdf5", seed=seed
        )
        return env

    return _init


env = DummyVecEnv([make_env_fn(seed) for seed in range(2)])
# env_fns = [make_env_fn(seed) for seed in range(2)]
# env = SubprocVecEnv(env_fns)

Created environment with name Stack_D0
Action size is 7


/scr/matthewh6/miniconda3/envs/pref/lib/python3.9/site-packages/gymnasium/spaces/box.py:235: UserWarning: WARN: Box low's precision lowered by casting to float32, current low.dtype=float64
  gym.logger.warn(
/scr/matthewh6/miniconda3/envs/pref/lib/python3.9/site-packages/gymnasium/spaces/box.py:305: UserWarning: WARN: Box high's precision lowered by casting to float32, current high.dtype=float64
  gym.logger.warn(


Created environment with name Stack_D0
Action size is 7


In [6]:
env.action_space.shape[0]

7

In [3]:
action_dim = env.action_space.shape[0]
actions = np.array([env.action_space.sample() for _ in range(env.num_envs)])
actions = actions.astype(np.float32)

In [ ]:
states = env.reset()

ValueError: not enough values to unpack (expected 2, got 1)

In [36]:
states["state"].shape

(2, 32)

In [ ]:
env.render().shape

(448, 224, 3)

In [ ]:
env.render_mode = "rgb_array"

[setattr(env, "render_mode", "rgb_array") for env in env.envs]

array([[[115, 113, 110],
        [114, 112, 108],
        [115, 112, 109],
        ...,
        [116, 114, 110],
        [116, 114, 111],
        [116, 114, 110]],

       [[116, 114, 111],
        [115, 112, 109],
        [115, 112, 109],
        ...,
        [116, 114, 111],
        [116, 115, 111],
        [116, 114, 110]],

       [[116, 114, 111],
        [115, 113, 110],
        [115, 113, 109],
        ...,
        [117, 115, 111],
        [116, 114, 110],
        [115, 113, 110]],

       ...,

       [[248, 247, 242],
        [247, 246, 241],
        [247, 245, 241],
        ...,
        [251, 251, 247],
        [251, 251, 246],
        [251, 251, 246]],

       [[247, 246, 242],
        [246, 247, 242],
        [247, 247, 242],
        ...,
        [250, 250, 245],
        [250, 250, 246],
        [252, 251, 247]],

       [[247, 247, 241],
        [248, 248, 244],
        [247, 247, 241],
        ...,
        [251, 252, 246],
        [251, 252, 247],
        [252, 251, 246]]

In [34]:
env.envs[1].render()

array([[[115, 113, 110],
        [114, 112, 108],
        [115, 112, 109],
        ...,
        [116, 114, 110],
        [116, 114, 111],
        [116, 114, 110]],

       [[116, 114, 111],
        [115, 112, 109],
        [115, 112, 109],
        ...,
        [116, 114, 111],
        [116, 115, 111],
        [116, 114, 110]],

       [[116, 114, 111],
        [115, 113, 110],
        [115, 113, 109],
        ...,
        [117, 115, 111],
        [116, 114, 110],
        [115, 113, 110]],

       ...,

       [[248, 247, 242],
        [247, 246, 241],
        [247, 245, 241],
        ...,
        [251, 251, 247],
        [251, 251, 246],
        [251, 251, 246]],

       [[247, 246, 242],
        [246, 247, 242],
        [247, 247, 242],
        ...,
        [250, 250, 245],
        [250, 250, 246],
        [252, 251, 247]],

       [[247, 247, 241],
        [248, 248, 244],
        [247, 247, 241],
        ...,
        [251, 252, 246],
        [251, 252, 247],
        [252, 251, 246]]

In [ ]:
import sys
import os
import numpy as np

custom_path = os.path.join(
    os.getcwd(), "/scr/matthewh6/robot_pref"
)  # or a relative/absolute path
if custom_path not in sys.path:
    sys.path.append(custom_path)
from utils.env import get_robomimic_env, wrap_env
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv, DummyVecEnv

env = get_robomimic_env(
    "/scr/shared/datasets/robot_pref/stack_mixed/stack_mixed.hdf5", seed=1
)

2025-07-20 23:22:30.242117: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-07-20 23:22:30.242189: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-07-20 23:22:30.242941: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-07-20 23:22:30.247163: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-07-20 23:22:30.916567: W tensorflow/compiler/tf2

ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /scr/matthewh6/robomimic/robomimic/scripts/setup_macros.py
)
Got error: No module named 'robosuite_task_zoo'
Created environment with name Stack_D0
Action size is 7


/scr/matthewh6/miniconda3/envs/pref/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [43]:
env.reset(seed=1)
env.env.state = state

In [44]:
state

{'state': array([-1.02849321e-01,  1.49308087e-02,  9.99075099e-01,  9.98050510e-01,
         2.48798509e-02,  5.72365253e-02,  3.91095432e-04,  2.08330000e-02,
        -2.08330000e-02,  4.08131502e-02,  3.16891598e-02,  8.30000000e-01,
         0.00000000e+00,  0.00000000e+00,  4.13004334e-01, -9.10729060e-01,
        -2.83710405e-02,  2.73262065e-02,  8.35000000e-01,  0.00000000e+00,
         0.00000000e+00,  9.88114116e-01,  1.53722129e-01,  1.43662471e-01,
         1.67583511e-02, -1.69075099e-01,  7.44782806e-02,  1.23953978e-02,
        -1.64075099e-01, -6.91841907e-02, -4.36295323e-03,  5.00000000e-03])}

In [ ]:
action = env.action_space.sample()

In [42]:
action[1] = -5
print(action)


[ 0 -5  1  0  1  0 -1]


In [39]:
s_1, _, _, _ = env.step(action)

In [40]:
s_1

{'state': array([-1.03422295e-01, -1.03488603e-02,  1.01609412e+00,  9.97015310e-01,
        -1.25508621e-02,  7.61770662e-02,  4.34956747e-05,  2.10458712e-02,
        -2.12008256e-02, -2.47724718e-02, -4.39936067e-02,  8.18456936e-01,
        -9.88673594e-20,  3.30545052e-19,  9.58062215e-01, -2.86560276e-01,
        -3.00368260e-02,  6.66088886e-02,  8.23456808e-01, -2.27551510e-19,
         6.63924653e-20,  2.80090490e-01, -9.59973602e-01,  7.86498232e-02,
        -3.36447465e-02, -1.97637187e-01,  7.33854690e-02,  7.69577488e-02,
        -1.92637315e-01, -5.26435415e-03,  1.10602495e-01,  4.99987202e-03])}

In [45]:
s_2, _, _, _ = env.step(action)

In [46]:
s_2

{'state': array([-1.14407634e-01, -1.84490239e-02,  1.01159946e+00,  9.98632548e-01,
        -1.10586208e-02,  5.07110804e-02,  6.25516645e-03,  2.10437689e-02,
        -2.12049355e-02, -4.03146307e-02,  5.62675000e-02,  8.18456936e-01,
         0.00000000e+00,  0.00000000e+00,  9.65257561e-01,  2.61300289e-01,
         1.86696107e-02, -4.26134177e-02,  8.23456808e-01,  7.91350008e-19,
         2.62543291e-19,  3.14888896e-01,  9.49128539e-01,  7.40930038e-02,
         7.47165239e-02, -1.93142521e-01,  1.33077245e-01, -2.41643938e-02,
        -1.88142649e-01,  5.89842414e-02, -9.88809177e-02,  4.99987202e-03])}

In [48]:
np.array_equal(s_1["state"], s_2["state"])


False

In [50]:
s_1["state"]

array([-1.03422295e-01, -1.03488603e-02,  1.01609412e+00,  9.97015310e-01,
       -1.25508621e-02,  7.61770662e-02,  4.34956747e-05,  2.10458712e-02,
       -2.12008256e-02, -2.47724718e-02, -4.39936067e-02,  8.18456936e-01,
       -9.88673594e-20,  3.30545052e-19,  9.58062215e-01, -2.86560276e-01,
       -3.00368260e-02,  6.66088886e-02,  8.23456808e-01, -2.27551510e-19,
        6.63924653e-20,  2.80090490e-01, -9.59973602e-01,  7.86498232e-02,
       -3.36447465e-02, -1.97637187e-01,  7.33854690e-02,  7.69577488e-02,
       -1.92637315e-01, -5.26435415e-03,  1.10602495e-01,  4.99987202e-03])

In [49]:
s_2["state"]

array([-1.14407634e-01, -1.84490239e-02,  1.01159946e+00,  9.98632548e-01,
       -1.10586208e-02,  5.07110804e-02,  6.25516645e-03,  2.10437689e-02,
       -2.12049355e-02, -4.03146307e-02,  5.62675000e-02,  8.18456936e-01,
        0.00000000e+00,  0.00000000e+00,  9.65257561e-01,  2.61300289e-01,
        1.86696107e-02, -4.26134177e-02,  8.23456808e-01,  7.91350008e-19,
        2.62543291e-19,  3.14888896e-01,  9.49128539e-01,  7.40930038e-02,
        7.47165239e-02, -1.93142521e-01,  1.33077245e-01, -2.41643938e-02,
       -1.88142649e-01,  5.89842414e-02, -9.88809177e-02,  4.99987202e-03])

In [59]:
"""
Convert from robomimic hdf5 to tensordict format
"""

import h5py
import torch
from tensordict import TensorDict
import numpy as np
import torch.nn.functional as F

save_dataset = True
data_path = "/scr/shared/datasets/robot_pref/stack_mixed/stack_mixed.hdf5"

with h5py.File(data_path, "r") as f:
    data = f["data"]
    print(list(data["demo_101"]["actions"]))

  

[array([-0.02893048,  0.51175438, -0.52793213, -0.41170738,  0.54071753,
        0.0238081 , -1.28340721]), array([ 0.91502052, -0.07488981, -0.44825067,  0.04202608,  0.66793144,
        0.65343403, -0.61415546]), array([ 0.55769832, -0.28759933, -0.34032087, -0.02635879,  0.1978352 ,
        0.84026086, -1.08499459]), array([ 0.42501529, -0.83674786, -0.36685147, -0.41009706,  0.92718762,
        0.54695836, -1.10843822]), array([ 0.19620703, -0.70485667, -0.48745453, -0.32879701,  0.3648507 ,
        1.13327447, -1.0200629 ]), array([ 0.27951257, -0.29863624, -0.30155285, -0.42097006,  0.54798811,
        0.6876719 , -0.1774365 ]), array([ 0.42420087, -0.57631778, -0.9987975 , -0.4128285 ,  0.44170918,
        0.80362541, -0.38728107]), array([ 0.49712654, -0.71367019,  0.26291408,  0.26530774,  0.07706068,
        0.4156698 , -1.7114847 ]), array([ 0.3866387 , -0.78359099,  0.65816074, -0.19300223, -0.14262759,
        0.14251257, -1.0798952 ]), array([ 0.0319601 ,  0.29699997, -0.